SELECT HACKERS.HACKER_ID, HACKERS.NAME, SUM(SUBMISSIONS.MAX_SCORE)AS TOTAL_SCORE 
FROM HACKERS INNER JOIN (SELECT HACKER_ID, CHALLENGE_ID, MAX(SCORE)AS MAX_SCORE FROM SUBMISSIONS GROUP BY HACKER_ID, CHALLENGE_ID)
AS SUBMISSIONS ON HACKERS.HACKER_ID=SUBMISSIONS.HACKER_ID
GROUP BY HACKERS.HACKER_ID, HACKERS.NAME
HAVING TOTAL_SCORE>0
ORDER BY TOTAL_SCORE DESC, HACKERS.HACKER_ID ASC;

