SELECT HACKERS.HACKER_ID, HACKERS.NAME FROM SUBMISSIONS 
JOIN CHALLENGES 
ON SUBMISSIONS.CHALLENGE_ID=CHALLENGES.CHALLENGE_ID 
JOIN DIFFICULTY
ON DIFFICULTY.DIFFICULTY_LEVEL=CHALLENGES.DIFFICULTY_LEVEL
JOIN HACKERS
ON HACKERS.HACKER_ID=SUBMISSIONS.HACKER_ID
WHERE SUBMISSIONS.SCORE=DIFFICULTY.SCORE
GROUP BY HACKERS.HACKER_ID, HACKERS.NAME
HAVING COUNT(SUBMISSIONS.HACKER_ID)>1
ORDER BY COUNT(SUBMISSIONS.HACKER_ID) DESC, SUBMISSIONS.HACKER_ID ASC;